### ISSUE TITLE
Suggested feature: clean final URL

### ISSUE THREAD

**Issue by tigattack** [seadfeng/redirect-checker#2]
Would you be interested in a feature to tidy up the final URL? As a user, I certainly would be. If so, I'd like to take a crack at it and PR.

What I had in mind was using [tidy-url](https://www.npmjs.com/package/@protontech/tidy-url) to clean it up and then do one of the following:
1. Automatically clean the URL and add it to the final result. For example:
	```
	URL: https://some.url/?utm_source=copy-link&ref=foo/bar_baz
	Clean URL: https://some.url/
	Status: 307
	Duration: 0.085 s
	```
2. Or add a checkbox that the user can select to tidy the returned URL transparently, resulting in the same final result structure, just with a tidy URL.

**Comment by seadfeng** [comment]
> Would you be interested in a feature to tidy up the final URL? As a user, I certainly would be. If so, I'd like to take a crack at it and PR.
> 
> What I had in mind was using [tidy-url](https://www.npmjs.com/package/@protontech/tidy-url) to clean it up and then do one of the following:
> 
> 1. Automatically clean the URL and add it to the final result. For example:
>    ```
>    URL: https://some.url/?utm_source=copy-link&ref=foo/bar_baz
>    Clean URL: https://some.url/
>    Status: 307
>    Duration: 0.085 s
>    ```
> 2. Or add a checkbox that the user can select to tidy the returned URL transparently, resulting in the same final result structure, just with a tidy URL.

Adding checkboxes is more appropriate, for some special needs, it is important to keep the URL parameter

**Comment by seadfeng** [comment]
> Would you be interested in a feature to tidy up the final URL? As a user, I certainly would be. If so, I'd like to take a crack at it and PR.
> 
> What I had in mind was using [tidy-url](https://www.npmjs.com/package/@protontech/tidy-url) to clean it up and then do one of the following:
> 
> 1. Automatically clean the URL and add it to the final result. For example:
>    ```
>    URL: https://some.url/?utm_source=copy-link&ref=foo/bar_baz
>    Clean URL: https://some.url/
>    Status: 307
>    Duration: 0.085 s
>    ```
> 2. Or add a checkbox that the user can select to tidy the returned URL transparently, resulting in the same final result structure, just with a tidy URL.

For cleaning up URLs, it is recommended to use regular expressions directly.

```js
const url='https://some.url/?utm_source=copy-link&ref=foo/bar_baz'
const cleanUrl = url.replace(/\?.*/,'');
```

**Comment by tigattack** [comment]
My idea wasn't necessarily to prune _all_ query parameters, just tracking and other "useless" parameters, for which the tidy-url package seems a nice fit.

**Comment by seadfeng** [comment]
> My idea wasn't necessarily to prune _all_ query parameters, just tracking and other "useless" parameters, for which the tidy-url package seems a nice fit.

Understood, your suggestion is great.

**Comment by seadfeng** [comment]
This feature has been processed

https://github.com/seadfeng/redirect-checker/releases/tag/0.1.9.rc

**Comment by fjl-cloud** [comment]
Running the project using npm run dev fails, how to solve it?
